twist_mux:
  ros__parameters:

    cmd_vel_out: /diff_drive_controller/cmd_vel_unstamped

    topics:
      nav2_f:
        topic  : /cmd_vel
        timeout: 0.5
        priority: 110
      nav2:
        topic  : /cmd_vel_nav
        timeout: 0.5
        priority: 118
      teleop:
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 150

    locks:
      emergency_stop:
        topic: /emergency_stop
        timeout: 0.0
        priority: 255
